site_title: AnyDSL

copyright: Saarland University

exclude:
  - LICENSE
  - README.md

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge

sass:
  style: compressed

toolbar:
  - Publications.md
  - Impala.md
  - Thorin.md

footer:
  logos:
    - image: images/uds_logo.svg
      url: https://www.uni-saarland.de
    - image: images/dfki_logo_e.svg
      url: https://www.dfki.de
  links:
    - title: Compiler Design Lab
      url: https://compilers.cs.uni-saarland.de
    - title: Computer Graphics Lab
      url: https://graphics.cg.uni-saarland.de
    - title: Agents and Simulated Reality
      url: https://www.dfki.de/en/web/research/research-departments/agents-and-simulated-reality
    - title: Imprint
      url: https://www.uni-saarland.de/en/legal-notice


repo_url: https://github.com/AnyDSL

github_edit_me_url: https://github.com/AnyDSL/anydsl.github.io/edit/master/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_toc: true
      site_title: AnyDSL
