


markdown: kramdown
kramdown:
  # Don't use a highlighter. This will output raw code blocks that can be
  # highlighted in javascript with CodeMirror.
  syntax_highlighter: none
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
