


markdown: kramdown
kramdown:
  # Don't use a highlighter. This will output raw code blocks that can be
  # highlighted in javascript with CodeMirror.
  syntax_highlighter: none
  auto_ids: true

toolbar:
  - Thorin.md
  - Impala.md
  - Publications.md

repo_url: https://github.com/AnyDSL

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      site_title: AnyDSL
